# Generated by Django 4.2.24 on 2025-10-28 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='methods/')),
                ('is_featured', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('bisection', 'Bisección'), ('newton', 'Newton-Raphson'), ('secant', 'Secante'), ('fixed_point', 'Punto Fijo'), ('pivot_partial', 'Pivoteo Parcial'), ('pivot_total', 'Pivoteo Total')], max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='methods.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
