# Generated by Django 5.1.2 on 2025-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='kind',
            field=models.CharField(choices=[('bisection', 'Bisection'), ('newton', 'Newton-Raphson'), ('secant', 'Secant'), ('fixed_point', 'Fixed Point'), ('false_position', 'False Position'), ('incremental_search', 'Incremental Search'), ('multiple_roots', 'Multiple Roots'), ('pivot_partial', 'Partial Pivoting'), ('pivot_total', 'Total Pivoting'), ('gaussian_elimination', 'Gaussian Elimination'), ('jacobi', 'Jacobi'), ('gauss_seidel', 'Gauss-Seidel'), ('sor', 'SOR'), ('crout', 'Crout Factorization'), ('doolittle', 'Doolittle Factorization'), ('cholesky', 'Cholesky Factorization'), ('lu_simple', 'Simple LU Factorization'), ('lu_pivot', 'Pivoting LU Factorization'), ('lagrange', 'Lagrange Interpolation'), ('vandermonde', 'Vandermonde Interpolation'), ('newton_interpolation', 'Newton Interpolation'), ('spline_linear', 'Linear Spline'), ('spline_quadratic', 'Quadratic Spline'), ('spline_cubic', 'Cubic Spline')], max_length=30),
        ),
    ]
